# Generated by Django 4.2.23 on 2025-08-22 11:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
        ('review', '0002_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'music')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'music')},
        ),
    ]
